# Generated by Django 3.1.1 on 2020-09-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200909_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
